### ISSUE TITLE
SIGINT (Ctrl+C) should be handled by opsdroid

### ISSUE THREAD

**Issue by gtseres** [opsdroid/opsdroid#247]
When executing opsdroid in Ubuntu or in a Docker container, the following message appears:
`(Press CTRL+C to quit)`

When hitting `Ctrl+C` though, the following traceback is produced:

```
^CERROR asyncio: Task exception was never retrieved
future: <Task finished coro=<ConnectorShell.listen() done, defined at /root/.opsdroid/modules/opsdroid-modules/connector/shell/__init__.py:57> exception=ConnectionResetError('Connection lost',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/root/.opsdroid/modules/opsdroid-modules/connector/shell/__init__.py", line 63, in listen
    user_input = await async_input('', opsdroid.eventloop)
  File "/root/.opsdroid/modules/opsdroid-modules/connector/shell/__init__.py", line 37, in async_input
    await writer.drain()
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 333, in drain
    yield from self._protocol._drain_helper()
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 204, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
ERROR asyncio: Exception in default exception handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1284, in call_exception_handler
    self.default_exception_handler(context)
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1259, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1314, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1421, in _log
    self.handle(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1431, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1493, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 861, in handle
    self.emit(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1053, in emit
    self.stream = self._open()
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1043, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Exception ignored in: <bound method Task.__del__ of <Task finished coro=<ConnectorShell.listen() done, defined at /root/.opsdroid/modules/opsdroid-modules/connector/shell/__init__.py:57> exception=ConnectionResetError('Connection lost',)>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 93, in __del__
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 234, in __del__
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1290, in call_exception_handler
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1314, in error
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1421, in _log
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1431, in handle
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1493, in callHandlers
  File "/usr/local/lib/python3.5/logging/__init__.py", line 861, in handle
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1053, in emit
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1043, in _open
NameError: name 'open' is not defined
ERROR asyncio: Task was destroyed but it is pending!
task: <Task pending coro=<parse_crontab() running at /usr/src/app/opsdroid/parsers/crontab.py:20> wait_for=<Future pending cb=[Task._wakeup()]>>
ERROR asyncio: Exception in default exception handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1284, in call_exception_handler
    self.default_exception_handler(context)
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1259, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1314, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1421, in _log
    self.handle(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1431, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1493, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 861, in handle
    self.emit(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1053, in emit
    self.stream = self._open()
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1043, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<parse_crontab() running at /usr/src/app/opsdroid/parsers/crontab.py:20> wait_for=<Future pending cb=[Task._wakeup()]>>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 92, in __del__
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1290, in call_exception_handler
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1314, in error
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1421, in _log
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1431, in handle
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1493, in callHandlers
  File "/usr/local/lib/python3.5/logging/__init__.py", line 861, in handle
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1053, in emit
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1043, in _open
NameError: name 'open' is not defined
```

This should be handled, so that opsdroid can exit gracefully without producing any tracebacks.

**Comment by jacobtomlinson** [comment]
I definitely agree. I had a look into this before and I think it's a bug in asyncio itself which is fixed in python 3.6. Perhaps it's worth moving the docker image onto 3.6.

**Comment by gtseres** [comment]
I have created a new image, based on Python 3.6: `FROM python:3.6-alpine`, but the issue still occurs

```
opsdroid> ^CERROR asyncio: Task was destroyed but it is pending!
task: <Task pending coro=<ConnectorShell.listen() running at /root/.opsdroid/modules/opsdroid-modules/connector/shell/__init__.py:63> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f29023f8528>()]> cb=[gather.<locals>._done_callback(0)() at /usr/local/lib/python3.6/asyncio/tasks.py:616]>
ERROR asyncio: Exception in default exception handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1285, in call_exception_handler
    self.default_exception_handler(context)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1260, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1069, in emit
    self.stream = self._open()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1291, in call_exception_handler
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1335, in error
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1442, in _log
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1452, in handle
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
  File "/usr/local/lib/python3.6/logging/__init__.py", line 863, in handle
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1069, in emit
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1059, in _open
NameError: name 'open' is not defined
ERROR asyncio: Task was destroyed but it is pending!
task: <Task pending coro=<parse_crontab() running at /usr/src/app/opsdroid/parsers/crontab.py:20> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f29023f85b8>()]> cb=[gather.<locals>._done_callback(1)() at /usr/local/lib/python3.6/asyncio/tasks.py:616]>
ERROR asyncio: Exception in default exception handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1285, in call_exception_handler
    self.default_exception_handler(context)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1260, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1069, in emit
    self.stream = self._open()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1291, in call_exception_handler
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1335, in error
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1442, in _log
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1452, in handle
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
  File "/usr/local/lib/python3.6/logging/__init__.py", line 863, in handle
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1069, in emit
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1059, in _open
NameError: name 'open' is not defined
```

With Python version being:
```
/usr/src/app # python --version
Python 3.6.2
```

**Comment by jacobtomlinson** [comment]
#254 appeared to fix but hasn't

**Comment by jacobtomlinson** [comment]
@gtseres you're definitely on the right lines. When the `SIGTERM` is sent the applications needs to exit gracefully. I just can't seem to find where to handle that.
