### ISSUE TITLE
Intermittent install failures in docker

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid#283]
Intermittently when trying to run with a docker container all modules fail to load with a `No module named 'opsdroid-modules'` error.

This must be related to how the python path is being appended to with the module path.

```
INFO opsdroid: ========================================
INFO opsdroid: Stated application
DEBUG opsdroid.loader: Loading modules from config
WARNING opsdroid.loader: No databases in configuration
DEBUG opsdroid.loader: Loading skill modules
DEBUG opsdroid.loader: Installing seen
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/seen'..."
DEBUG opsdroid.loader: b'error: could not lock config file /root/.opsdroid/modules/opsdroid-modules/skill/seen/.git/config: No such file or directory'
DEBUG opsdroid.loader: b"fatal: could not set 'remote.origin.fetch' to '+refs/heads/*:refs/remotes/origin/*'"
DEBUG opsdroid.loader: Install of seen failed
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.seen.seen
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.seen
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.seen
ERROR opsdroid.loader: Module seen failed to import
DEBUG opsdroid.loader: Installing dance
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/dance'..."
DEBUG opsdroid.loader: Installed dance to /root/.opsdroid/modules/opsdroid-modules/skill/dance
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.dance.dance
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.dance
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.dance
ERROR opsdroid.loader: Module dance failed to import
DEBUG opsdroid.loader: Installing loudnoises
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/loudnoises'..."
DEBUG opsdroid.loader: Installed loudnoises to /root/.opsdroid/modules/opsdroid-modules/skill/loudnoises
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.loudnoises.loudnoises
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.loudnoises
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.loudnoises
ERROR opsdroid.loader: Module loudnoises failed to import
DEBUG opsdroid.loader: Installing apiai
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/apiai'..."
DEBUG opsdroid.loader: Installed apiai to /root/.opsdroid/modules/opsdroid-modules/skill/apiai
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.apiai.apiai
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.apiai
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.apiai
ERROR opsdroid.loader: Module apiai failed to import
DEBUG opsdroid.loader: Installing weather
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/weather'..."
DEBUG opsdroid.loader: Installed weather to /root/.opsdroid/modules/opsdroid-modules/skill/weather
DEBUG opsdroid.loader: b'You must give at least one requirement to install (see "pip help install")'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.weather.weather
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.weather
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.weather
ERROR opsdroid.loader: Module weather failed to import
DEBUG opsdroid.loader: Installing grafana
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/grafana'..."
DEBUG opsdroid.loader: Installed grafana to /root/.opsdroid/modules/opsdroid-modules/skill/grafana
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.grafana.grafana
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.grafana
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.grafana
ERROR opsdroid.loader: Module grafana failed to import
DEBUG opsdroid.loader: Installing travis
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/travis'..."
DEBUG opsdroid.loader: Installed travis to /root/.opsdroid/modules/opsdroid-modules/skill/travis
DEBUG opsdroid.loader: b'Collecting pyOpenSSL (from -r /root/.opsdroid/modules/opsdroid-modules/skill/travis/requirements.txt (line 1))'
DEBUG opsdroid.loader: b'  Downloading pyOpenSSL-17.3.0-py2.py3-none-any.whl (51kB)'
DEBUG opsdroid.loader: b'Collecting cryptography>=1.9 (from pyOpenSSL->-r /root/.opsdroid/modules/opsdroid-modules/skill/travis/requirements.txt (line 1))'
DEBUG opsdroid.loader: b'  Downloading cryptography-2.1.1.tar.gz (441kB)'
DEBUG opsdroid.loader: b'Collecting six>=1.5.2 (from pyOpenSSL->-r /root/.opsdroid/modules/opsdroid-modules/skill/travis/requirements.txt (line 1))'
DEBUG opsdroid.loader: b'  Downloading six-1.11.0-py2.py3-none-any.whl'
DEBUG opsdroid.loader: b'Collecting idna>=2.1 (from cryptography>=1.9->pyOpenSSL->-r /root/.opsdroid/modules/opsdroid-modules/skill/travis/requirements.txt (line 1))'
DEBUG opsdroid.loader: b'  Downloading idna-2.6-py2.py3-none-any.whl (56kB)'
DEBUG opsdroid.loader: b'Collecting asn1crypto>=0.21.0 (from cryptography>=1.9->pyOpenSSL->-r /root/.opsdroid/modules/opsdroid-modules/skill/travis/requirements.txt (line 1))'
DEBUG opsdroid.loader: b'  Downloading asn1crypto-0.23.0-py2.py3-none-any.whl (99kB)'
DEBUG opsdroid.loader: b'Collecting cffi>=1.7 (from cryptography>=1.9->pyOpenSSL->-r /root/.opsdroid/modules/opsdroid-modules/skill/travis/requirements.txt (line 1))'
DEBUG opsdroid.loader: b'  Downloading cffi-1.11.2.tar.gz (435kB)'
DEBUG opsdroid.loader: b'    Complete output from command python setup.py egg_info:'
DEBUG opsdroid.loader: b'    '
DEBUG opsdroid.loader: b'        No working compiler found, or bogus compiler options passed to'
DEBUG opsdroid.loader: b'        the compiler from Python\'s standard "distutils" module.  See'
DEBUG opsdroid.loader: b'        the error messages above.  Likely, the problem is not related'
DEBUG opsdroid.loader: b'        to CFFI but generic to the setup.py of any Python package that'
DEBUG opsdroid.loader: b'        tries to compile C code.  (Hints: on OS/X 10.8, for errors about'
DEBUG opsdroid.loader: b'        -mno-fused-madd see http://stackoverflow.com/questions/22313407/'
DEBUG opsdroid.loader: b'        Otherwise, see https://wiki.python.org/moin/CompLangPython or'
DEBUG opsdroid.loader: b'        the IRC channel #python on irc.freenode.net.)'
DEBUG opsdroid.loader: b'    '
DEBUG opsdroid.loader: b'    ----------------------------------------'
DEBUG opsdroid.loader: b'Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-srjp58lw/cffi/'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.travis.travis
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.travis
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.travis
ERROR opsdroid.loader: Module travis failed to import
DEBUG opsdroid.loader: Installing github
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/github'..."
DEBUG opsdroid.loader: Installed github to /root/.opsdroid/modules/opsdroid-modules/skill/github
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.github.github
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.github
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.github
ERROR opsdroid.loader: Module github failed to import
DEBUG opsdroid.loader: Installing food
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/food'..."
DEBUG opsdroid.loader: Installed food to /root/.opsdroid/modules/opsdroid-modules/skill/food
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.food.food
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.food
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.food
ERROR opsdroid.loader: Module food failed to import
DEBUG opsdroid.loader: Installing please-stand-by
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/please-stand-by'..."
DEBUG opsdroid.loader: Installed please-stand-by to /root/.opsdroid/modules/opsdroid-modules/skill/please-stand-by
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.please-stand-by.please-stand-by
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.please-stand-by
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.please-stand-by
ERROR opsdroid.loader: Module please-stand-by failed to import
DEBUG opsdroid.loader: Installing magpi
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/magpi'..."
DEBUG opsdroid.loader: Installed magpi to /root/.opsdroid/modules/opsdroid-modules/skill/magpi
DEBUG opsdroid.loader: b'Collecting beautifulsoup4 (from -r /root/.opsdroid/modules/opsdroid-modules/skill/magpi/requirements.txt (line 1))'
DEBUG opsdroid.loader: b'  Downloading beautifulsoup4-4.6.0-py3-none-any.whl (86kB)'
DEBUG opsdroid.loader: b'Installing collected packages: beautifulsoup4'
DEBUG opsdroid.loader: b'Successfully installed beautifulsoup4-4.6.0'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.magpi.magpi
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.magpi
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.magpi
ERROR opsdroid.loader: Module magpi failed to import
DEBUG opsdroid.loader: Installing iss
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/iss'..."
DEBUG opsdroid.loader: Installed iss to /root/.opsdroid/modules/opsdroid-modules/skill/iss
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.iss.iss
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.iss
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.iss
ERROR opsdroid.loader: Module iss failed to import
DEBUG opsdroid.loader: Installing word-of-the-day
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/word-of-the-day'..."
DEBUG opsdroid.loader: Installed word-of-the-day to /root/.opsdroid/modules/opsdroid-modules/skill/word-of-the-day
DEBUG opsdroid.loader: b'Collecting feedparser==5.2.1 (from -r /root/.opsdroid/modules/opsdroid-modules/skill/word-of-the-day/requirements.txt (line 1))'
DEBUG opsdroid.loader: b'  Downloading feedparser-5.2.1.zip (1.2MB)'
DEBUG opsdroid.loader: b'Building wheels for collected packages: feedparser'
DEBUG opsdroid.loader: b'  Running setup.py bdist_wheel for feedparser: started'
DEBUG opsdroid.loader: b"  Running setup.py bdist_wheel for feedparser: finished with status 'done'"
DEBUG opsdroid.loader: b'  Stored in directory: /root/.cache/pip/wheels/15/ce/10/b500f745822ea6db6ea8ed225c06b15c000d71016b89ef9037'
DEBUG opsdroid.loader: b'Successfully built feedparser'
DEBUG opsdroid.loader: b'Installing collected packages: feedparser'
DEBUG opsdroid.loader: b'Successfully installed feedparser-5.2.1'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.word-of-the-day.word-of-the-day
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.word-of-the-day
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.word-of-the-day
ERROR opsdroid.loader: Module word-of-the-day failed to import
DEBUG opsdroid.loader: Installing location
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/location'..."
DEBUG opsdroid.loader: Installed location to /root/.opsdroid/modules/opsdroid-modules/skill/location
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.location.location
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.location
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.location
ERROR opsdroid.loader: Module location failed to import
DEBUG opsdroid.loader: Installing google-it
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/google-it'..."
DEBUG opsdroid.loader: Installed google-it to /root/.opsdroid/modules/opsdroid-modules/skill/google-it
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.google-it.google-it
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load skill opsdroid-modules.skill.google-it
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load skill opsdroid-modules.skill.google-it
ERROR opsdroid.loader: Module google-it failed to import
DEBUG opsdroid.loader: Loading connector modules
DEBUG opsdroid.loader: Installing slack
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/connector/slack'..."
DEBUG opsdroid.loader: Installed slack to /root/.opsdroid/modules/opsdroid-modules/connector/slack
DEBUG opsdroid.loader: b'Collecting slacker-asyncio (from -r /root/.opsdroid/modules/opsdroid-modules/connector/slack/requirements.txt (line 1))'
DEBUG opsdroid.loader: b'  Downloading slacker-asyncio-0.8.7.tar.gz'
DEBUG opsdroid.loader: b'Collecting websockets==3.2 (from -r /root/.opsdroid/modules/opsdroid-modules/connector/slack/requirements.txt (line 2))'
DEBUG opsdroid.loader: b'  Downloading websockets-3.2-py33.py34.py35-none-any.whl'
DEBUG opsdroid.loader: b'Collecting aiohttp==0.21.6 (from slacker-asyncio->-r /root/.opsdroid/modules/opsdroid-modules/connector/slack/requirements.txt (line 1))'
DEBUG opsdroid.loader: b'  Downloading aiohttp-0.21.6.tar.gz (528kB)'
DEBUG opsdroid.loader: b'Collecting chardet (from aiohttp==0.21.6->slacker-asyncio->-r /root/.opsdroid/modules/opsdroid-modules/connector/slack/requirements.txt (line 1))'
DEBUG opsdroid.loader: b'  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)'
DEBUG opsdroid.loader: b'Building wheels for collected packages: slacker-asyncio, aiohttp'
DEBUG opsdroid.loader: b'  Running setup.py bdist_wheel for slacker-asyncio: started'
DEBUG opsdroid.loader: b"  Running setup.py bdist_wheel for slacker-asyncio: finished with status 'done'"
DEBUG opsdroid.loader: b'  Stored in directory: /root/.cache/pip/wheels/43/1f/56/9bba991d347a16bded6ab4eda7fc9622b30763987c029f0a79'
DEBUG opsdroid.loader: b'  Running setup.py bdist_wheel for aiohttp: started'
DEBUG opsdroid.loader: b"  Running setup.py bdist_wheel for aiohttp: finished with status 'done'"
DEBUG opsdroid.loader: b'  Stored in directory: /root/.cache/pip/wheels/05/ee/ec/85b3fc1e0527943b7647b46c66057ec479d5ad2ac24964b60f'
DEBUG opsdroid.loader: b'Successfully built slacker-asyncio aiohttp'
DEBUG opsdroid.loader: b'Installing collected packages: chardet, aiohttp, slacker-asyncio, websockets'
DEBUG opsdroid.loader: b'Successfully installed aiohttp-0.21.6 chardet-3.0.4 slacker-asyncio-0.8.7 websockets-3.2'
DEBUG opsdroid.loader: Failed to load connector opsdroid-modules.connector.slack.slack
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load connector opsdroid-modules.connector.slack
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load connector opsdroid-modules.connector.slack
ERROR opsdroid.loader: Module slack failed to import
DEBUG opsdroid.loader: Installing websocket
DEBUG opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/connector/websocket'..."
DEBUG opsdroid.loader: Installed websocket to /root/.opsdroid/modules/opsdroid-modules/connector/websocket
DEBUG opsdroid.loader: b'You must give at least one requirement to install (see "pip help install")'
DEBUG opsdroid.loader: Failed to load connector opsdroid-modules.connector.websocket.websocket
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
DEBUG opsdroid.loader: Failed to load connector opsdroid-modules.connector.websocket
DEBUG opsdroid.loader: No module named 'opsdroid-modules'
ERROR opsdroid.loader: Failed to load connector opsdroid-modules.connector.websocket
ERROR opsdroid.loader: Module websocket failed to import
DEBUG opsdroid.core: Loaded 0 skills
CRITICAL opsdroid.core: All connectors failed to load
INFO opsdroid.core: Exiting application with return code 1
DEBUG asyncio: Using selector: EpollSelector
Error: All connectors failed to load
```

Config file

```yaml
##                      _           _     _
##   ___  _ __  ___  __| |_ __ ___ (_) __| |
##  / _ \| '_ \/ __|/ _` | '__/ _ \| |/ _` |
## | (_) | |_) \__ \ (_| | | | (_) | | (_| |
##  \___/| .__/|___/\__,_|_|  \___/|_|\__,_|
##       |_|
##                   __ _
##   ___ ___  _ __  / _(_) __ _
##  / __/ _ \| '_ \| |_| |/ _` |
## | (_| (_) | | | |  _| | (_| |
##  \___\___/|_| |_|_| |_|\__, |
##                        |___/
##
## A default config file to use with opsdroid

timezone: 'Europe/London'

## Set the logging level
logging:
  level: debug
  path: false
  console: true

web:
  host: '0.0.0.0'

## Set the location for opsdroid to install modules
module-path: "/root/.opsdroid/modules"

parsers:
  - name: apiai
    access-token: $APIAI_ACCESS_TOKEN
    min-score: 0.6

## Connector modules
connectors:
  - name: slack
    default-room: '#general'
    bot-name: "labby 2.0"
    icon-emoji: ":rat:"
    api-token: $SLACK_ACCESS_TOKEN

  - name: websocket
    bot-name: "labby 2.0"

## Database modules (optional)
# databases:

## Skill modules
skills:

  ## Last seen (https://github.com/opsdroid/skill-seen)
  - name: seen

  ## Dance (https://github.com/opsdroid/skill-dance)
  - name: dance

  ## Loud noises (https://github.com/opsdroid/skill-loudnoises)
  - name: loudnoises

  - name: apiai
    include:
      - "smalltalk"
    exclude:
      - "smalltalk.confirmation"

  - name: weather
    repo: "https://github.com/met-office-lab/opsdroid-skill-weather.git"

  - name: grafana
    room: "#monitoring"

  - name: travis
    room: "#monitoring"

  - name: github

  - name: food
    api-key: $FOOD2FORK_API_KEY

  - name: please-stand-by

  - name: magpi
    room: "#random"

  - name: iss
    api-key: $ISS_NOW_API_KEY
    map-type: "hybrid"

  - name: word-of-the-day

  - name: location
    repo: "https://github.com/met-office-lab/opsdroid-skill-location.git"
    auth-token: $LAB_LOCATION_AUTH_TOKEN
    url: <redacted>
  - name: google-it
```

**Comment by vitkhab** [comment]
How to reproduce this problem?
After running `docker run --rm -v /tmp/configuration.yml:/etc/opsdroid/configuration.yaml:ro opsdroid/opsdroid:latest` I get 14 loaded skills and no errors like `No module named 'opsdroid-modules`
https://gist.github.com/vitkhab/4423e2d21c1b7dee3c52cc108199dc1e

**Comment by jacobtomlinson** [comment]
You're getting a slack auth error as I would expect as you've set the token to `0`. As you say you're not getting the `No module named 'opsdroid-modules` error.

I'm only getting this error intermittently. I'm deploying on kubernetes so there may be some subtle differences there. If you repeatedly clean up your images and then run that script again so you get consistent results?

I'm wondering if there is some kind of race conditions going on causing this error to only happen occasionally.

**Comment by vitkhab** [comment]
I ran container several times both from DockerHub image and from image built from GitHub locally. And I've never had such error.
Yes, I run it with wrong API tokens, but I don't think it affects module loading anyhow. 

Can you fully describe how you deploy the app?

**Comment by jacobtomlinson** [comment]
I'm using helm to deploy on kubernetes. The chart template for the deployment looks like this:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: labby-{{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: labby
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - image: opsdroid/opsdroid:{{ .Values.opsdroid.version }}
          imagePullPolicy: Always
          name: labby
          ports:
            - containerPort: {{ .Values.opsdroid.port }}
          volumeMounts:
            - name: config
              mountPath: "/root/.opsdroid"
              readOnly: false
          livenessProbe:
            httpGet:
              path: /stats
              port: {{ .Values.opsdroid.port }}
            initialDelaySeconds: 120
            periodSeconds: 10
          env:
            {{- range .Values.opsdroid.environment }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: labby-config
                  key: {{ .name }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.opsdroid.resources.requests.cpu }}
              memory: {{ .Values.opsdroid.resources.requests.memory }}
      volumes:
        - name: config
          configMap:
            name: labby-config
```

**Comment by FabioRosado** [comment]
@jacobtomlinson I believe this issue is related with the #281 the main issue is that two try/except in the loader, after @suprithIUB fixes the issue those intermittent installs should be fixed as well.

I could provide a temporary fix to this issue (the suggestion to move the try/except inside the first one) until suprithIUB gets a better solution 😃

**Comment by jacobtomlinson** [comment]
Still seeing this issue in the latest dev build. It all seems to be related to a failure in creating the skills directories. Sometimes it fails complaining about unable to `pip install` the requirements which have come in the module, despite the code explicitly checking for the `requirements.txt` file before running `pip`.

Also there are occasionally git errors in the logs and then the error around not being able to import `opsdroid-modules`.

```

INFO opsdroid: ========================================
INFO opsdroid: Stated application
WARNING opsdroid: 'welcome-message: true/false' is missing in configuration.yaml
DEBUG opsdroid.loader: Loading modules from config...
WARNING opsdroid.loader: No databases in configuration.
DEBUG opsdroid.loader: Loading skill modules...
DEBUG opsdroid.loader: Installing seen...
INFO opsdroid.loader: Cloning from remote repository
DEBUG opsdroid.loader: b"Cloning into '/root/.opsdroid/modules/opsdroid-modules/skill/seen'..."
DEBUG opsdroid.loader: b'error: could not lock config file /root/.opsdroid/modules/opsdroid-modules/skill/seen/.git/config: No such file or directory'
DEBUG opsdroid.loader: b"fatal: could not set 'remote.origin.fetch' to '+refs/heads/*:refs/remotes/origin/*'"
ERROR opsdroid.loader: Install of seen failed.
DEBUG asyncio: Using selector: EpollSelector
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/opsdroid/__main__.py", line 135, in <module>
    main()
  File "/usr/src/app/opsdroid/__main__.py", line 130, in main
    opsdroid.start_loop()
  File "/usr/src/app/opsdroid/core.py", line 133, in start_loop
    self.loader.load_modules_from_config(self.config)
  File "/usr/src/app/opsdroid/loader.py", line 211, in load_modules_from_config
    skills = self._load_modules('skill', config['skills'])
  File "/usr/src/app/opsdroid/loader.py", line 264, in _load_modules
    module = self.import_module(config)
  File "/usr/src/app/opsdroid/loader.py", line 46, in import_module
    if config["name"] and importlib.util.find_spec(config["module_path"]):
  File "/usr/local/lib/python3.5/importlib/util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ImportError: No module named 'opsdroid-modules'
```

**Comment by jacobtomlinson** [comment]
This issue seems to be a problem in the way kubernetes mounts [configMaps](https://kubernetes.io/docs/tasks/configure-pod-container/configmap/). These maps get mounted as a directory where the keys are files and the values are the contents of the files. In the above config we are mounting a config map to `/root/.opsdroid`. This directory is also being written to by opsdroid when installing modules and this is where things are going wrong, it is likely that the mount is not fully available at the time that opsdroid is trying to write to it. A workaround for this is to constrain the configMap to the single key we want (`configuration.yaml`).

So

```yaml
volumeMounts:
  - name: config
    mountPath: "/root/.opsdroid"
    readOnly: false
```

becomes

```yaml
volumeMounts:
  - name: config
    mountPath: "/root/.opsdroid/configuration.yaml"
    subPath: configuration.yaml
    readOnly: false
```
